version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/vagrant/nginx/conf.d:/etc/nginx/conf.d"
      - "/vagrant/ssl/:/etc/nginx/ssl/"
      - "/vagrant/nginx/logs:/var/log/nginx"
      - "/vagrant/www:/usr/share/www:rw"
  php:
    container_name: php
    build:
        context: ../php/php72
    ports:
      - "9000:9000"
      - "9501:9501"
    working_dir: "/usr/share/www"
    volumes:
      - "/vagrant/www:/usr/share/www:rw"
      - "/vagrant/php/php72/php/php.ini:/usr/local/etc/php/php.ini"
      - "/vagrant/php/php72/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "/vagrant/php/php72/logs/:/var/log/"
  apache1:
    container_name: apache1
    build:
      context: ../apache
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "/vagrant/www:/usr/share/www/"
      - "/vagrant/apache/sites-enabled/:/etc/apache2/sites-enabled/"
      - "/vagrant/ssl/:/etc/apache2/ssl/"
      - "/vagrant/apache/log/:/var/log/apache2/"
  apache2:
    container_name: apache2
    build:
      context: ../apache
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - "/vagrant/www:/usr/share/www/"
      - "/vagrant/apache/sites-enabled/:/etc/apache2/sites-enabled/"
      - "/vagrant/ssl/:/etc/apache2/ssl/"
      - "/vagrant/apache/log/:/var/log/apache2/"
  mysql:
    container_name: mysql
    image: mysql:5
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wh10t#p


volumes:
  mysql: