version: "3"

services:
  dnsmasq:
    container_name: dnsmasq
    image: jpillora/dnsmasq:latest
    ports:
      - "53:53/udp"
      - "5380:8080"
    volumes:
      - "/vagrant/dnsmasq/dnsmasq.d/:/etc/dnsmasq.d/"
      - "/vagrant/dnsmasq/resolv.conf:/etc/resolv.conf"
      - "/vagrant/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf"
    networks:
      frontend:
        ipv4_address: 172.20.0.2
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "8090:8090"
      - "443:443"
    volumes:
      - "/vagrant/nginx/conf.d:/etc/nginx/conf.d"
      - "/vagrant/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/vagrant/nginx/ssl/:/etc/nginx/cert/"
      - "logs:/var/log/nginx"
      - "/vagrant/www/:/usr/share/www/"
    labels:
      aliyun.logs.stdout: stdout
      aliyun.logs.access: /var/log/nginx/*.log
  php72:
      container_name: php72
      build:
          context: php/php72
      working_dir: "/usr/share/www"
      volumes:
        - "/vagrant/www/:/usr/share/www/"
        - "/vagrant/docker/php/php72/php-fpm.d/www.conf:/etc/php/7.2/fpm/pool.d/www.conf"
        - "/vagrant/docker/php/php72/php/php.ini:/etc/php/7.2/fpm/php.ini"
      networks:
        default:
          ipv4_address: 172.18.0.8
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
        - "/vagrant/redis/redis.conf:/usr/local/etc/redis/redis.conf"
  mysql:
    container_name: mysql
    image: mysql:5
    user: 1000:1000
    ports:
      - "3306:3306"
    volumes:
      - "/vagrant/storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wh10t#p
  log-pilot:
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/:/host"
    privileged: true
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  logs:
      driver: local
      driver_opts:
        type: none
        device: /vagrant/logs
        o: bind